language: node_js
os: linux
dist: xenial

node_js:
  - 10
  - 12
  - 14

before_install:
  - npm config set depth 0
script:
  - npm run test
  - 'if [ -n "${LINT-}" ]; then npm run eslint; fi'
env:
  jobs:
    - ESLINT=7
jobs:
  fast_finish: true
  include:
    - node_js: 'lts/*'
      env: LINT=true

#  exclude:
#    - node_js: 6
#      env: ESLINT=6
